# Generated by Django 4.2.2 on 2023-06-26 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_task_delete_mytodo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mytodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
