# Generated by Django 4.2.2 on 2023-06-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_mytodo_delete_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytodo',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
